name: Install Chocolatey, Python 2, and Node.js 16

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Chocolatey
        shell: pwsh
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force
          [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12; 
          iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))

      - name: Check and Install Python 2
        shell: pwsh
        run: |
          if (-not (choco list --local-only | Select-String "python2")) {
            choco install python2 -y
          } else {
            Write-Host "Python 2 is already installed."
          }

      - name: Check and Install Node.js 16
        shell: pwsh
        run: |
          if (-not (choco list --local-only | Select-String "nodejs")) {
            choco install nodejs --version=16.20.0 -y
          } else {
            Write-Host "Node.js 16 is already installed."
          }

      - name: Verify Python 2 Installation
        shell: pwsh
        run: python2 --version

      - name: Verify Node.js Installation
        shell: pwsh
        run: node --version

      - name: Install Node.js Packages
        shell: pwsh
        run: |
          npm install -g node-gyp
          node-gyp configure --verbose