name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm ci  

      - name: Run eslint & prettier (Windows)
        if: runner.os == 'Windows'  # Only runs on Windows
        run: npm run lint:win
        shell: pwsh  

      - name: Run eslint & prettier (Linux/Mac)
        if: runner.os != 'Windows'  # Runs on Ubuntu or macOS
        run: npm run lint:posix
        shell: bash  

      - name: Install Playwright
        run: |
          npx playwright install --with-deps chromium

      - name: Build
        run: npm run build

      - name: Run tests
        run: npm test