name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}  # Use the OS from the matrix

    strategy:
      matrix:
        os: [ubuntu-20.04, macos-latest, windows-latest]  # Define the OS matrix

    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-node@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
          node-version: 18

      - name: Run eslint & prettier
        run: |
          npm ci
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            npm run lint:win 
          else
            npm run lint:posix
          fi
          npm run format

      - run: |
          npx playwright install --with-deps chromium

      - name: Build
        run: npm run build

      - name: Run tests
        run: npm test