name: Install Chocolatey, Python 2, and Node.js 16

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Chocolatey
        shell: pwsh
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force
          [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12; 
          iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))

      - name: Install Python 2
        shell: pwsh
        run: choco install python2 -y

      - name: Uninstall Current Node.js
        shell: pwsh
        run: choco uninstall nodejs -y

      - name: Install Node.js 16
        shell: pwsh
        run: choco install nodejs --version=16.20.0 -y

      - name: Verify Python 2 Installation
        shell: pwsh
        run: python2 --version

      - name: Verify Node.js Installation
        shell: pwsh
        run: node --version

      - name: Install Node.js Packages
        shell: pwsh
        run: |
          npm install -g node-gyp
          node-gyp configure --verbose