name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
          node-version: 18
      - run: | 
         npx playwright install --with-deps
         npm install
      - run: npm test
